/**
 * Action type for successful retrieval of all Charity List.
 */
export const GET_ALL_CHARITY_LIST_SUCCESS = "GET_CHARITY_LIST_SUCCESS";

/**
 * Action type for failed retrieval of all Charity List.
 */
export const GET_ALL_CHARITY_LIST_FAILURE = "GET_CHARITY_LIST_FAILURE";
/**
 * Action type for Reset retrieval of all Charity List.
 */
export const GET_ALL_CHARITY_LIST_RESET = "GET_CHARITY_LIST_RESET";


export const GET_BLOG_DROPDOWN_DATA_SUCCESS = "GET_BLOG_DROPDOWN_DATA_SUCCESS";
export const GET_BLOG_DROPDOWN_DATA_FAILURE = "GET_BLOG_DROPDOWN_DATA_FAILURE";

export const ADD_EDIT_CHARITY_DETAILS_SUCCESS = "ADD_EDIT_CHARITY_DETAILS_SUCCESS";
export const ADD_EDIT_CHARITY_DETAILS_FAILURE = "ADD_EDIT_CHARITY_DETAILS_FAILURE";


export const GET_MY_CHARITY_LIST_SUCCESS = "GET_MY_CHARITY_LIST_SUCCESS";
export const GET_MY_CHARITY_LIST_FAUILURE = "GET_MY_CHARITY_LIST_FAUILURE";
export const GET_MY_CHARITY_RESET = "GET_MY_CHARITY_RESET";

export const APPROVE_CHYARITY_REQUEST_SUCCESS = "APPROVE_CHYARITY_REQUEST_SUCCESS";
export const APPROVE_CHYARITY_REQUEST_FAILURE = "APPROVE_CHYARITY_REQUEST_FAILURE";