
export const GET_ALL_BLOGS_LIST_SUCCESS = "GET_ALL_BLOGS_LIST_SUCCESS";
export const GET_ALL_BLOGS_LIST_FAILURE = "GET_ALL_BLOGS_LIST_FAILURE";
export const RESET_ALL_BLOG_LIST = "RESET_ALL_BLOG_LIST";

export const GET_MY_BLOGS_LIST_SUCCESS = "GET_MY_BLOGS_LIST_SUCCESS";
export const GET_MY_BLOGS_LIST_FAILURE = "GET_MY_BLOGS_LIST_FAILURE";
export const RESET_MY_BLOG_LIST = "RESET_MY_BLOG_LIST";


export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAILURE = "DELETE_BLOG_FAILURE";

export const UPDATE_BLOG_STATUS_SUCCESS = "UPDATE_BLOG_STATUS_SUCCESS";
export const UPDATE_BLOG_STATUS_FAILURE = "UPDATE_BLOG_STATUS_FAILURE";

export const APPROVE_REJECT_BLOG_SUCCESS = "APPROVE_REJECT_BLOG_SUCCESS";
export const APPROVE_REJECT_BLOG_FAILURE = "APPROVE_REJECT_BLOG_FAILURE";

export const ADD_EDIT_BLOG_SUCCESS = "ADD_EDIT_BLOG_SUCCESS";
export const ADD_EDIT_BLOG_FAILURE = "ADD_EDIT_BLOG_FAILURE";


