export const GET_MY_CHARITY_LIST_SUCCESS = "GET_MY_CHARITY_LIST_SUCCESS";
export const GET_MY_CHARITY_LIST_FAUILURE = "GET_MY_CHARITY_LIST_FAUILURE";
export const GET_MY_CHARITY_RESET = "GET_MY_CHARITY_RESET";